### PR TITLE
vtun: make hostnames case-insensitive

### PR DESCRIPTION
**Pull request by USA-RedDragon**
We accomplish this by converting all the strings to lowercase on parse and to lowercase before looking it up in the list.

Context:

> One of the biggest pain points I've had with running an aredn tunnel is the hostname checking vtun does. Several times I've had tunnel users reset their hardware and change the capitalization of their node knocking them off the network. I made a vtun patch to internally lowercase hostnames before matching to effectively make the host case-insensitive to vtun. 

This patch is exported from https://github.com/USA-RedDragon/vtun/commit/3af435c8f6e4b3f3cd91ab1b1327a7973d9f9add (if you would like to see the commit in context)

### CODE REVIEW

**Review by aanon4 — APPROVED** [review]
Going to trust the changing these strings in-place doesn't have any unexpected side effects.

**Comment by USA-RedDragon** [comment]
I'm actually not 100% certain. Observably "it works", but that doesn't hold much weight on it's own. I should probably `strdup` the `$1` and pass that to the `parse_host->host` just to be safe

**Comment by USA-RedDragon** [comment]
Also added a break-out for the while loop since it's not _technically_ finite without it.

**Review by aanon4 — APPROVED** [review]

**Comment by aanon4** [comment]
@USA-RedDragon I had to revert this patch as I'm getting reports that tunnels running this code will no longer connect to tunnels running the older code.

**Comment by USA-RedDragon** [comment]
Any details? Is it the client side or server side that's having issues? Any logs from the event? I'd be glad to look into it.

**Comment by USA-RedDragon** [comment]
I'm thinking newer client older server might be the situation after reviewing the code again. Vtun client might be sending a normalized lowercase hostname to the older server that's still case sensitive. I'll need to see how vtun handles that hostname because I intended for only the internal host list to be lowercase, not anything sent over the wire

Granted, this is an assumption. I'll set up my two nodes in a few different configs and see what's up

**Comment by USA-RedDragon** [comment]
Okay I figured out how to work around that. Working on a patch that adds a normalized hostname while parsing the config (keeping the original non-normalized host in place since there's no way to tell from the client side if a server supports normalization without changing the protocol). Then any operations the search the host list will try the standard hostname first, THEN if it fails it'll try the normalized version instead, which should keep backwards compatibility properly

**Pull request merged**
